all : exo21 exo22

exo21 : main.cpp Semaphore_2019.h
	g++ -Wall -std=c++1y -pthread -g -O0 main.cpp -o exo21

exo22 : main2.cpp Semaphore_2019.h
	g++ -Wall -std=c++1y -pthread -g -O0 main2.cpp -o exo22

clean :
	\rm exo21 exo22

